services:
  fluent-bit:
    image: fluent/fluent-bit:3.0.4
    environment:
      - ES_HOST=elasticsearch
    volumes:
      - ./etc/:/fluent-bit/etc/
    ports:
      - "8888:8888"
      - "2020:2020"
    depends_on:
      - elasticsearch
    labels:
      kompose.service.expose: true

  elasticsearch:
    image: elasticsearch:6.5.4
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2048m"
    mem_limit: 4096m

  kibana:
    image: kibana:6.5.4
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    labels:
      kompose.service.expose: true
