version: "3.7"

services:
  fluent-bit:
    image: fluent/fluent-bit
    environment:
      - ES_HOST=elasticsearch
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./expand_logs.lua:/fluent-bit/etc/expand_logs.lua
    ports:
      - "8888:8888"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:6.5.4
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node

  kibana:
    image: kibana:6.5.4
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
