version: "3.7"

services:
  fluent-bit:
    image: fluent/fluent-bit
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./expand_logs.lua:/fluent-bit/etc/expand_logs.lua
    ports:
      - "8888:8888"
